name: notifiable
description: A simple widget that allows updating specific widgets instead of the whole widget tree.
version: 1.0.9
homepage: https://github.com/ShoutOutSoftware/Notifiable-Flutter

environment:
  sdk: '>=2.14.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
